export const ERROR_CODES = {
  // Generic HTTP errors
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SERVER_ERROR: 'SERVER_ERROR',

  // Category specific errors
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_HAS_COURSES: 'CATEGORY_HAS_COURSES',
  CATEGORY_INVALID_POSITION: 'CATEGORY_INVALID_POSITION',
  CATEGORY_NOT_SOFT_DELETED: 'CATEGORY_NOT_SOFT_DELETED',
  CATEGORY_RESTORE_FAILED: 'CATEGORY_RESTORE_FAILED',
  CATEGORY_NO_IDS_PROVIDED: 'CATEGORY_NO_IDS_PROVIDED',
  CATEGORY_NOT_FOUND_MULTIPLE: 'CATEGORY_NOT_FOUND_MULTIPLE',

  // Position / status update errors
  CATEGORY_POSITION_UPDATE_FAILED: 'CATEGORY_POSITION_UPDATE_FAILED',
  CATEGORY_STATUS_UPDATE_FAILED: 'CATEGORY_STATUS_UPDATE_FAILED',
};

export const TABLE_RELATIONS = { COURSE: 'course', LESSON: 'lesson' };
